spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/topwulian_com?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        allow: 127.0.0.1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: localhost
    port: 6379
    password: root
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: 123
    password: 123
    protocol: smtp
    test-connection: false
#    properties:
#      mail.smtp.auth: true
  activemq:
      broker-url: tcp://localhost:61616 # 消息组件的连接主机信息
mybatis:
  type-aliases-package: com.topwulian.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
files:
  path: ${file-path:d:/files}
logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/admin-server.log
  maxsize: 30MB
token:
  expire:
    seconds: 86400
server:
  tomcat:
    uri-encoding: UTF-8
  port: 9001
  servlet:
    session:
      timeout: 300m #30分钟，测试的话时间不能太短，否则不准。m是分钟单位，s是秒的单位，h是小时的单位，不写单位的话默认是毫秒
http:
  maxTotal: 100 #最大连接数
  defaultMaxPerRoute: 20  #并发数
  connectTimeout: 1000 #创建连接的最长时间
  connectionRequestTimeout: 500 #从连接池中获取到连接的最长时间
  socketTimeout: 10000 #数据传输的最长时间

#业务相关参数
jzwl:
  mq:
    queue: queue_gather  #@RabbitListener(queues = {"${jzwl.mq.queue}"})
  kfk:
    domain: www.kaifakuai.com #开发快的服务器
    app_key: 123 #开发快的key
    secret_key: 123  #开发快的秘钥
    uid: 123  #我们程序中用来接收开发快消息的uid 嘉穗的为prod中的
    receive_uid: 123 #嘉穗的已部署好,这是我自己测试的

file:
  local:
    path: /Users/szz/IdeaProjects/cloud-service/localFile
    prefix: /statics
    urlPrefix: http://localhost:8080/api-f${file.local.prefix}
  aliyun:
    endpoint: 123
    accessKeyId: 123
    accessKeySecret: 123
    bucketName: 123
    domain: 123.0.0.1